typography_spectrum: 0.31514045083895326
color:
  brandStrength: 0.2059438752476126
  lightness: 0.05178920761682093
  saturation: 0.800255085574463
  rhythmicContrast: 0.47112518618814647
  brandColors:
    - '#7D8A2E'
    - '#C9D787'
    - '#FFFFFF'
    - '#FFC0A9'
    - '#FF8598'
opengraph:
  type: main page
  appId: freedomtour
layout_spectrum: 0.8573725051246583
author:
  name: Mick Benson
  email: mickbenson@hotmail.com
  url: freedomtour.co.uk
name: Freedom Tour
title: Adventure 1st Class
